language: r
dist: trusty
sudo: false

cache:
  packages: yes
  directories:
    - $HOME/bin

before_script:
  - Rscript -e 'blogdown::install_hugo()'

script:
  - Rscript -e 'blogdown::build_site()'

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: master